### ISSUE TITLE
Segmentation fault with  supervised

### ISSUE THREAD

**Issue by amirshams84** [rmenegaux/fastDNA#5]
I am trying to build a model with your proposed data set(small one) with the following command
`../fastDNA/fastdna supervised -input train_small-db.fasta -labels train_small-db.species-level.taxid -output model`

Read sequence n1564, NC_010515       
Number of sequences: 1564
Number of labels: 193
Number of words: 0
Segmentation fault

**Comment by rmenegaux** [comment]
Hi @amirshams84 this is a bug: k-mer length `minn` is 0 by default. I will fix this.

In the mean time you can just specify `minn`:
```../fastDNA/fastdna supervised -input train_small-db.fasta -labels train_small-db.species-level.taxid -output model -minn 10```
should work fine.

**Comment by rmenegaux** [comment]
Fixed in master
