### ISSUE TITLE
Quantizing model using python implementation

### ISSUE THREAD

**Issue by RA-Tsagairt** [rmenegaux/fastDNA#6]
Hello,

i have trained several models using your code but they are all really large file sizes. To shrink their memory footprint I am using the command:

python fastDNA/fdna.py -quantize -model_name ~/path_to_model -train_fasta ~/path_to_train_fasta

but it returns the error:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
Traceback (most recent call last):
  File "fastDNA/fdna.py", line 163, in <module>
    ft.quantize(model_path, args.train_fasta)
  File "fastDNA/python/fastDNA/fastDNA.py", line 67, in quantize
    return timed_check_call(command, name=readout, verbose=self.verbose)
  File "fastDNA/python/fastDNA/fastDNA.py", line 13, in timed_check_call
    subprocess.check_call(command, shell=True)
  File "/home/secuser/anaconda3/envs/bio_glove/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'fastDNA/fastdna quantize -input /home/secuser/Rob/bio-predictor-development/fasta_files/25_10_21/train_bf10_C100_L500.fasta -output /home/secuser/Rob/bio-predictor-development/fast_dna/output/models/fdna_k14_d50_e500_lr0.1_n4.0 -qnorm' returned non-zero exit status 134.

I have tried this with various models and their respective training files; all returns the same error. Model sizes are ~20GB.

**Comment by rmenegaux** [comment]
Hi!

I ran a quick test on the master branch and the quantize command you indicate works, so the problem must be elsewhere.

The std::bad_alloc error is a bummer usually, but here are 2 possible causes I can think of:
- You are running out of memory (how much RAM does your CPU have?)
- The model you are trying to quantize is itself faulty.  Does it work, i.e. can you make predictions with it?

Hope this helps

**Comment by RA-Tsagairt** [comment]
Hi!

Thanks for getting back to me. In answer to your questions:

- The CPU has 64GB of RAM
- The model performs excellently on predictions

I suspect it has something to do with file paths not being located correctly. I'll try a fresh install and see if that magically solves the issue. I'll let you know how that goes.

**Comment by RA-Tsagairt** [comment]
Hi!,

Update: It is now working with the fresh installation. Don't know what the issue could have been!

Thanks :)

**Comment by rmenegaux** [comment]
Great!
